/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VcRouteImport } from './routes/vc'
import { Route as TopInvestorsRouteImport } from './routes/top-investors'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as FounderRouteImport } from './routes/founder'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as CashRouteImport } from './routes/cash'
import { Route as AiResearchRouteImport } from './routes/ai-research'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StartupSlugRouteImport } from './routes/startup.$slug'
import { Route as AiResearchCompanyIdRouteImport } from './routes/ai-research.$companyId'

const VcRoute = VcRouteImport.update({
  id: '/vc',
  path: '/vc',
  getParentRoute: () => rootRouteImport,
} as any)
const TopInvestorsRoute = TopInvestorsRouteImport.update({
  id: '/top-investors',
  path: '/top-investors',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderRoute = FounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const CashRoute = CashRouteImport.update({
  id: '/cash',
  path: '/cash',
  getParentRoute: () => rootRouteImport,
} as any)
const AiResearchRoute = AiResearchRouteImport.update({
  id: '/ai-research',
  path: '/ai-research',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StartupSlugRoute = StartupSlugRouteImport.update({
  id: '/startup/$slug',
  path: '/startup/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AiResearchCompanyIdRoute = AiResearchCompanyIdRouteImport.update({
  id: '/$companyId',
  path: '/$companyId',
  getParentRoute: () => AiResearchRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-research': typeof AiResearchRouteWithChildren
  '/cash': typeof CashRoute
  '/discover': typeof DiscoverRoute
  '/founder': typeof FounderRoute
  '/messages': typeof MessagesRoute
  '/portfolio': typeof PortfolioRoute
  '/profile': typeof ProfileRoute
  '/top-investors': typeof TopInvestorsRoute
  '/vc': typeof VcRoute
  '/ai-research/$companyId': typeof AiResearchCompanyIdRoute
  '/startup/$slug': typeof StartupSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-research': typeof AiResearchRouteWithChildren
  '/cash': typeof CashRoute
  '/discover': typeof DiscoverRoute
  '/founder': typeof FounderRoute
  '/messages': typeof MessagesRoute
  '/portfolio': typeof PortfolioRoute
  '/profile': typeof ProfileRoute
  '/top-investors': typeof TopInvestorsRoute
  '/vc': typeof VcRoute
  '/ai-research/$companyId': typeof AiResearchCompanyIdRoute
  '/startup/$slug': typeof StartupSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-research': typeof AiResearchRouteWithChildren
  '/cash': typeof CashRoute
  '/discover': typeof DiscoverRoute
  '/founder': typeof FounderRoute
  '/messages': typeof MessagesRoute
  '/portfolio': typeof PortfolioRoute
  '/profile': typeof ProfileRoute
  '/top-investors': typeof TopInvestorsRoute
  '/vc': typeof VcRoute
  '/ai-research/$companyId': typeof AiResearchCompanyIdRoute
  '/startup/$slug': typeof StartupSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-research'
    | '/cash'
    | '/discover'
    | '/founder'
    | '/messages'
    | '/portfolio'
    | '/profile'
    | '/top-investors'
    | '/vc'
    | '/ai-research/$companyId'
    | '/startup/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-research'
    | '/cash'
    | '/discover'
    | '/founder'
    | '/messages'
    | '/portfolio'
    | '/profile'
    | '/top-investors'
    | '/vc'
    | '/ai-research/$companyId'
    | '/startup/$slug'
  id:
    | '__root__'
    | '/'
    | '/ai-research'
    | '/cash'
    | '/discover'
    | '/founder'
    | '/messages'
    | '/portfolio'
    | '/profile'
    | '/top-investors'
    | '/vc'
    | '/ai-research/$companyId'
    | '/startup/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiResearchRoute: typeof AiResearchRouteWithChildren
  CashRoute: typeof CashRoute
  DiscoverRoute: typeof DiscoverRoute
  FounderRoute: typeof FounderRoute
  MessagesRoute: typeof MessagesRoute
  PortfolioRoute: typeof PortfolioRoute
  ProfileRoute: typeof ProfileRoute
  TopInvestorsRoute: typeof TopInvestorsRoute
  VcRoute: typeof VcRoute
  StartupSlugRoute: typeof StartupSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vc': {
      id: '/vc'
      path: '/vc'
      fullPath: '/vc'
      preLoaderRoute: typeof VcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/top-investors': {
      id: '/top-investors'
      path: '/top-investors'
      fullPath: '/top-investors'
      preLoaderRoute: typeof TopInvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder': {
      id: '/founder'
      path: '/founder'
      fullPath: '/founder'
      preLoaderRoute: typeof FounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash': {
      id: '/cash'
      path: '/cash'
      fullPath: '/cash'
      preLoaderRoute: typeof CashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-research': {
      id: '/ai-research'
      path: '/ai-research'
      fullPath: '/ai-research'
      preLoaderRoute: typeof AiResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/startup/$slug': {
      id: '/startup/$slug'
      path: '/startup/$slug'
      fullPath: '/startup/$slug'
      preLoaderRoute: typeof StartupSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-research/$companyId': {
      id: '/ai-research/$companyId'
      path: '/$companyId'
      fullPath: '/ai-research/$companyId'
      preLoaderRoute: typeof AiResearchCompanyIdRouteImport
      parentRoute: typeof AiResearchRoute
    }
  }
}

interface AiResearchRouteChildren {
  AiResearchCompanyIdRoute: typeof AiResearchCompanyIdRoute
}

const AiResearchRouteChildren: AiResearchRouteChildren = {
  AiResearchCompanyIdRoute: AiResearchCompanyIdRoute,
}

const AiResearchRouteWithChildren = AiResearchRoute._addFileChildren(
  AiResearchRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiResearchRoute: AiResearchRouteWithChildren,
  CashRoute: CashRoute,
  DiscoverRoute: DiscoverRoute,
  FounderRoute: FounderRoute,
  MessagesRoute: MessagesRoute,
  PortfolioRoute: PortfolioRoute,
  ProfileRoute: ProfileRoute,
  TopInvestorsRoute: TopInvestorsRoute,
  VcRoute: VcRoute,
  StartupSlugRoute: StartupSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
